### PR TITLE
Add ability to play a song without navigating

### PR DESCRIPTION
**Pull request by ItsErikSquared**
This adds a new setting toggle to allow you to hold the "CTRL" key down while in the search bar to play a song without navigating away from your current page. (I thought it was neat feature and wanted to share)

### CODE REVIEW

**Review by jeroentvb — COMMENTED** [review]
I really like the addition of pressing ctrl and not navigating. I do think that that functionality should be standard when enabling the `play suggestion on click` setting, because having 2 options that do the same but in a slightly different way is a bit confusing.

So in the new situation there would be no `If the ctrl is held while selecting an item, play without navigating.` setting, but the ctrl+click functionality would just work whenever `play suggestion on click` is enabled.

Oh, and would you mind running `npm run lint:fix` after your next commit, or having eslint fix on save?

**Comment by ItsErikSquared** [comment]
You are completely correct about the one setting vs. two. 

I removed the setting and merged it into the original play suggestion on click. I also added the detection for a ctrl + mouse click - Initially it was only for ctrl+enter.

Apologies about the lint.

**Comment by jeroentvb** [comment]
> Apologies about the lint.

No worries, I would ultimately like to have a github action fix that automatically on each PR if needed, but haven't come around to figuring that out.

As for as for the current state of the PR, everything is great, except using ctrl+click doesn't seem to be triggering any event on macOs with the latest spotify and spicetify. Does that work for you?

**Comment by ItsErikSquared** [comment]
It is indeed working for me, however I am using Windows. I was also able to test with a Linux installation which worked as well. Sadly I do not have a macOS environment to test on.

I (a non-mac user) have a mac question; there is two separate keys - `command` and `ctrl` - Is it possible that the `command` key is being pressed rather than `ctrl` or being interpreted as command rather than `ctrl`? If I recall correctly most shortcuts use `command` rather than `ctrl` on mac.

As I'm writing this maybe its better to also check if the 'Meta' key (which is mac's ⌘ key and windows' start key) is being pressed as well alongside `ctrl`.

Testing version info:
```
Windows 11 Pro 22H2
Spotify for Windows 1.1.81.604.gccacfc8c
Spicetify 2.9.5

Ubuntu 21.10 (Impish) x86_64
Spotify version 1.1.72.439.gc253025e (latest from via apt)
Spicetify 2.9.1 (latest compatible)
```

**Pull request merged**
